title: Wayside Mapping
tagline: Open source geospatial services by Quincy Morgan
permalink: /:path/
url: "http://localhost:4000"
liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true
source: _source
date_format: "%b %e, %Y"
plugins:
  - absolute-urls
  - jekyll-target-blank
  - manual-markdown
  - unwrap-img
target-blank:
   noopener: false
   noreferrer: false
collections:
  pages:
    output: true
  projects:
    output: true
defaults:
  - scope:
      path: _pages
      type: pages
    values:
      permalink: /:path/
      layout: page
  - scope:
      path: _posts
      type: posts
    values:
      permalink: /blog/:slug/
      layout: post
  - scope:
      path: _projects
      type: projects
    values:
      permalink: /projects/:path/
      layout: project
email: quincy@waysidemapping.org
youtube_page: "@waysidemapping"
twitch: waysidemapping
wikipedia: Quincylvania
github: waysidemapping
kofi: waysidemapping
openstreetmap: quincylvania
linkedin: quincy-morgan
slack_page: /slack/
bluesky: waysidemapping.org
mastodon: waysidemapping@mastodon.social
facebook: waysidemapping
instagram: waysidemapping
threads: waysidemapping
rss: /feed.xml